name: Test Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r git_hub_test/requirements.txt
    - name: Test with pytest
      run: |
        pytest git_hub_test/tests/test_main.py
