def words():
    words = {
        "a": ["apple", "apricot", "ant", "airplane", "arrow", "acorn", "almond", "ash", "ankle", "alpaca"],
        "b": ["banana", "blueberry", "bird", "book", "balloon", "butterfly", "beaver", "bass", "bubble", "bear"],
        "c": ["carrot", "cherry", "cat", "computer", "crown", "camel", "coconut", "cypress", "chicken", "cattle"],
        "d": ["dragonfruit", "date", "dog", "desk", "diamond", "donkey", "daisy", "dolphin", "doughnut", "deer"],
        "e": ["eggplant", "elderberry", "elephant", "envelope", "eagle", "emu", "evergreen", "ear", "elbow", "earth"],
        "f": ["fig", "fruit", "fox", "fan", "flag", "flamingo", "frog", "fish", "feather", "ferret"],
        "g": ["grape", "guava", "giraffe", "guitar", "globe", "gazelle", "goose", "grouper", "gum", "goat"],
        "h": ["honeydew", "huckleberry", "horse", "hat", "heart", "hawk", "hyena", "hickory", "hippopotamus", "hand"],
        "i": ["iceberg lettuce", "indigo apple", "iguana", "igloo", "insect", "island", "iris", "ibis", "ice cream", "iron"],
        "j": ["jackfruit", "jujube", "jaguar", "jacket", "jellyfish", "junebug", "javelin", "jay", "jam", "jester"],
        "k": ["kiwi", "kumquat", "kangaroo", "key", "kite", "koala", "kelp", "kingwood", "kitten", "knight"],
        "l": ["lemon", "lime", "lion", "laptop", "leaf", "llama", "lychee", "larch", "leg", "lake"],
        "m": ["mango", "melon", "monkey", "map", "moon", "moose", "mushroom", "magnolia", "mouth", "mountain"],
        "n": ["nectarine", "nut", "newt", "notebook", "needle", "nest", "nandu", "narwhal", "nacho", "napkin"],
        "o": ["orange", "olive", "otter", "ocean", "owl", "oak", "onion", "ostrich", "oyster", "oil"],
        "p": ["pineapple", "peach", "penguin", "pencil", "planet", "porcupine", "panda", "pork", "pearl", "panther"],
        "q": ["quince", "quail", "queen", "quilt", "quokka"],
        "r": ["race", "radar", "rain", "raise", "rake", "ramble", "random", "range", "rank", "rapid",  "rare", "rate", "rather", "raven", "reach", "read", "ready", "real", "rebel", "recall", "receive", "recent", "reckon", "recognize", "recommend", "record", "recover", "red",         "reduce", "refer", "reflect", "refuse", "regard", "register", "regret", "regular",          "reject", "relate", "relax", "release", "relevant", "rely", "remain", "remember",         "remind", "remove", "render", "repair", "repeat", "replace", "reply", "report",       "represent", "request", "require", "rescue", "research", "reserve", "reside",         "resist", "resolve", "respect", "respond", "rest", "restore", "result", "resume",        "retain", "retire", "return", "reveal", "review", "revise", "reward", "rhythm",        "ribbon", "rice", "rich", "ride", "rifle", "right", "ring", "rip", "rise", "risk",        "river", "road", "roar", "rock", "rocket", "role", "roll", "roof", "room", "rope",        "rose", "rough", "round", "route", "row", "royal", "rub", "ruin", "rule", "run",        "rush", "rust", "ruthless", "rythm"],
        "s": ["sad", "safe", "said", "sail", "salary", "sale", "salt", "same", "sample", "sand",        "satisfy", "save", "say", "scale", "scare", "scatter", "scene", "schedule", "scheme",        "school", "science", "scope", "score", "scratch", "scream", "screen", "script",        "scroll", "sea", "search", "season", "seat", "second", "secret", "section",        "security", "see", "seed", "seek", "seem", "segment", "seize", "select", "self",        "sell", "send", "senior", "sense", "sentence", "separate", "sequence", "series",        "serious", "serve", "session", "set", "settle", "seven", "several", "severe",        "shade", "shadow", "shake", "shall", "shallow", "shame", "shape", "share",        "sharp", "she", "shed", "sheep", "sheet", "shelf", "shell", "shelter", "shift",        "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop", "short", "should",        "shout", "show", "shower", "shrink", "shut", "sibling", "sick", "side", "sight",        "sign", "signal", "significant", "silence", "silent", "silk", "silly", "silver",        "similar", "simple", "since", "sing", "single", "sink", "sister", "sit", "site",        "situation", "size", "skill", "skin", "skip", "sky", "slam", "sleep", "slice",        "slide", "slight", "slip", "slow", "small", "smart", "smile", "smoke", "smooth",        "snake", "snap", "sneak", "snow", "so", "soap", "soar", "soccer", "social", "society",        "sock", "soft", "software", "soil", "soldier", "solid", "solution", "solve", "some",        "somebody", "someday", "somehow", "someone", "something", "sometimes", "somewhere",        "son", "song", "soon", "sophisticated", "sorry", "sort", "sound", "soup", "source",        "south", "space", "spare", "speak", "special", "species", "specific", "speech",        "speed", "spell", "spend", "sphere", "spill", "spin", "spirit", "split", "spoil",        "spoon", "sport", "spot", "spread", "spring", "spy", "square", "squeeze", "stable",        "staff", "stage", "stair", "stake", "stand", "star", "stare", "start", "state",        "statement", "station", "stay", "steal", "steam", "steel", "step", "stick",        "still", "stomach", "stone", "stop", "store", "storm", "story", "stove",        "straight", "strange"],    
        "t": ["time", "today", "tomorrow", "together", "train", "tree", "talk", "tennis", "team", "teacher", "technology", "tiger", "table", "test", "travel", "truth", "trust", "tool", "town", "top"],
        "u": ["under", "umbrella", "unique", "university", "universe", "uncle", "ugly", "up", "urge", "use", "understand", "unicorn", "ultimate", "unusual", "upcoming", "user", "united", "upgrade", "urban", "utter"],
        "v": ["value", "victory", "vehicle", "vacation", "village", "vase", "velvet", "voice", "vast", "very", "versatile", "visit", "vitamin", "violin", "volume", "vine", "volcano", "venture", "virtual", "visionary"],
        "w": ["water", "world", "wind", "winter", "work", "walk", "watch", "wife", "wood", "warm", "wonder", "wallet", "western", "welcome", "wish", "wealthy", "wash", "wire", "weather", "wheat"],
        "x": ["x-ray", "xenophobia", "xenon", "xylophone", "x-axis", "xerophyte", "xeric", "xylem", "xanthophyll", "x-ray diffraction"],
        "y": ["year", "yellow", "young", "yes", "yesterday", "yoga", "yacht", "yard", "yawn", "you", "yolk", "yarn", "yearning", "yield", "youth", "yuletide", "yummy", "yearbook", "yodel"],
        "z": ["zebra", "zoom", "zone", "zipper", "zero", "zoo", "zodiac", "zenith", "zinc", "zesty", "zigzag", "zeal", "zombie", "zillion", "zucchini", "zenithal", "zoology", "zonal", "zipperless"]
            

    }